name: CMake_Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: 
 build:
 
  runs-on: ubuntu-latest
  permissions:
    contents: write

  steps:
  - uses: actions/checkout@v4
    
  - name: Build Docker image
    run: docker build -t message-writer .

  - name: Run Docker container
    run: docker run --name message-writer-container message-writer

  - name: Copy output file
    run: docker cp message-writer-container:/usr/src/app/output.txt ./output.txt

  - name: Display output file
    run: cat ./output.txt
